# External host
apiVersion: v1
kind: Service
metadata:
  name: machine-host
spec:
  type: ExternalName
  externalName: host.docker.internal
---
# Config map
apiVersion: v1
kind: ConfigMap
metadata:
  name: go-gin-config
data:
  REDIS_URI: machine-host:6379
---
# deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-gin-deploy
  labels:
    project: go-gin-pj-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      project: go-gin-pj-pod
  minReadySeconds: 20
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        project: go-gin-pj-pod # pod label
    spec:
      containers:
        - name: web
          imagePullPolicy: Always
          image: kenwong0729/go-gin-ping:latest
          ports:
            - containerPort: 8080
          env:
            - name: REDIS_URI
              valueFrom:
                configMapKeyRef:
                  name: go-gin-config
                  key: REDIS_URI
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
---
# Load balancer
apiVersion: v1
kind: Service
metadata:
  name: go-gin-deploy
spec:
  type: LoadBalancer
  selector:
    project: go-gin-pj-pod
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 8080
