// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"crab-dev/simple-go-gin/configs"
	"crab-dev/simple-go-gin/controllers"
	"crab-dev/simple-go-gin/controllers/albums"
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
)

// Injectors from wire.go:

func CreateApp() (*Application, error) {
	detailsController := albums.NewDetailsController()
	initControllers := albums.CreateInitControllersFn(detailsController)
	engine := configs.InitRouter(initControllers)
	application, err := AppSet(engine)
	if err != nil {
		return nil, err
	}
	return application, nil
}

// wire.go:

func AppSet(router *gin.Engine) (*Application, error) {
	return &Application{
		router,
	}, nil
}

var providerSet = wire.NewSet(configs.CacheSet, configs.RouterSet, controllers.ControllerSet, AppSet)
